Note From: wluongo@liquidweb.com [root@db2.dooce.com] 

* * /scripts/mysqlbackupscript 0 4 * * * /scripts/mysqlbackuprotate

[root@db2.dooce.com] mysqlbackups >> cat /scripts/mysqlbackupscript

#!/bin/bash
# compresses backups with date in filename, ftps to remote server
# this script requires ssh keys to be setup between localhost and remotehost

DATE=`date +%Y%m%d-%H` REMOTEHOST="192.168.0.1" mysqldump --all-databases |
gzip -c > /backup/mysqlbackups/$DATE.sql.gz scp
/backup/mysqlbackups/$DATE.sql.gz
root@$REMOTEHOST:/backup/mysqlbackups/$DATE.sql.gz [root@db2.dooce.com]
mysqlbackups >> cat /scripts/mysqlbackuprotate

#!/bin/bash
# rotates the backups generated by mysqlbackupscript
#this script will remove any backups older than $AGEINDAYS
AGEINDAYS=5

find /backup/mysqlbackups/ -mtime $AGEINDAYS -exec rm -f {} \;


Note From: wluongo@liquidweb.com root@host [/backup/mysqlbackups]#
hostname host.dooce.com root@host [/backup/mysqlbackups]# crontab -l

0 3 * * * /root/bin/backupdbs.sh >/dev/null 2>&1 
0 4 * * * /scripts/mysqlbackuprotate

root@host [/backup/mysqlbackups]# cat /scripts/mysqlbackuprotate
#!/bin/bash
# rotates the backups generated by mysqlbackupscript
#this script will remove any backups older than $AGEINDAYS
AGEINDAYS=5
find /backup/mysqlbackups/ -mtime $AGEINDAYS -exec rm -f {} \;

