#System Information Checker
#Displays Server Info
#Created By: Mark Benedict
#!/bin/bash

clear
echo "System Information Checker - v0.1"
echo "Mark Benedict"
echo "------------------------------------------"
echo "Server Name - `hostname`"
echo "Server Time - `date`"
echo "------------------------------------------"
echo "Basic Hardware -"
echo "CPUs Availible: `lscpu |grep "CPU(s):" |awk '{ print $2 }' |head -1`@ `cat /proc/cpuinfo |grep @ | awk '{ print $9 }'`"
echo "RAM  Availible: `free -m |sed -n '2p' |awk '{ print $2 }'`MB"
echo "Harddrive: `df -h |sed -n '1p'| awk '{ print $2,$3,$4,$5 }'` "
echo "             `df -h |sed -n '2p'| awk '{ print $2, $3,$4,$5 }'` "
echo ""
echo "Cpanel Details -"
echo "Cpanel Version: `/usr/local/cpanel/cpanel -V`"
echo "Domains/Subdomains: `cat /etc/userdomains | awk '{print $1}' | wc -l`"
echo ""
echo "Linux Details -"
echo "OS Version:  `cat /etc/*release |head -1`"
echo "Kernel Version: `uname -r`"
echo ""
echo "Apache Details -"
echo "Apache Version: `httpd -v |awk '{ print $3 }' |head -1`"
echo ""
echo "Mysql Details -"
echo "Mysql Version: `mysql -V |awk '{ print $5 }'`"
echo ""
echo "PHP Details -"
echo "PHP Version: `php -v |grep "(built:" |awk '{ print $2 }'`"
echo "PHP Handler: `/usr/local/cpanel/bin/rebuild_phpconf --current |grep "PHP5 SAPI:" |awk '{ print $3 }'`"
echo "memory_limit: `php -i |grep memory_limit |awk '{ print $5 }'`"
echo "upload_max_filesize: `php -i |grep upload_max_filesize |awk '{ print $5 }'`"
echo ""
echo "Perl Details -"
echo "Perl Version: `perl -v |grep "This is perl," |awk '{ print $4 }'`"
echo ""
echo "Python Details -"
echo "`python --version` "
